# Site settings
name: Karthi J
title: Karthi J | Back End Software Engineer
description: Supportive and reliable team player with a strong bias towards Software Quality and Project Deliverables
url: https://karthij15.github.io/
baseurl: ''
email: karthij.upgrade@gmail.com
cover: https://karthij15.github.io/img/og.png
logo: https://karthij15.github.io/img/emojis/technologist.png
resume: https://karthij15.github.io/resume.pdf
social:
  - title: email
    url: mailto:karthij.upgrade@gmail.com
  - title: github
    url: https://github.com/karthij15
  - title: linkedin
    url: https://www.linkedin.com/in/karthi-janaki-raman-b32b21142

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
